### ISSUE TITLE
Investigate blank map

### ISSUE THREAD

**Issue by rafinkanisa** [iMMAP/DRR-datacenter#11]
As a follow-up action point to support the capacity-building team to deliver the training of Natural Hazard and Geometeorological before this award is ending by the end of this month, we'll need to make ASDC temporarily accept new users.
Within the meeting, it has been mentioned that the following map is showing blank
http://asdc.immap.org/maps/6399/view

Kindly investigate and let me know whether this was a bug or not

**Comment by sud0su** [comment]
That's because when creating the map, the owner didn't choose the layers that you want to use as layers in the interactive map (I already tried it directly, and the result is the same, it's blank like the interactive map topography)
