### ISSUE TITLE
Hide Security Category

### ISSUE THREAD

**Issue by rafinkanisa** [iMMAP/DRR-datacenter#13]
As a follow-up action point to support the capacity-building team to deliver the training of Natural Hazard and Geometeorological before this award is ending by the end of this month, we'll need to make ASDC temporarily accept new users.
It is also required to hide anything related to security.

Because we'll only have a short time to do it, I would propose to temporarily hide any category related with security.
After the training is finished, we'll put this category back and will hide the category in an appropriate manner once we start working for the new award.

TO DO:

- [x] Hide any categories related with Security
- [x] After the training is finished, put back the category to be visible

Additional Screenshots
![image](https://user-images.githubusercontent.com/28089698/152523328-6769e4b6-ee65-4a23-b9b4-c88fe4fd14d9.png)

**Comment by dodiws** [comment]
Resources (layers, static maps, interactive maps) in security category has been made hidden/private.

**Comment by rafinkanisa** [comment]
Hi. I heard from Daniel that the training is finished. Please put back the category to be visible @dodiws

**Comment by dodiws** [comment]
Resources in security category has been re-made visible to public.
