### ISSUE TITLE
Update Drought Data

### ISSUE THREAD

**Issue by rafinkanisa** [iMMAP/DRR-datacenter#16]
As part of re-activating the ASDC to humanitarian organization, we'll have to update all of the outdated data in ASDC to the most recent one

TODO :

- [x] Create Script to update the drought data
- [x] Perform drought data update

**Comment by dodiws** [comment]
- test drought update script in local, using local db
- looking for ways to monitor celery task log to help on debugging since drought script takes long processing time and celery task sometime not working

**Comment by mishaker** [comment]
@dodiws please include the script you wrote to update the db here in this issue. thanks

**Comment by dodiws** [comment]
[This commit](https://github.com/iMMAP/DRR-datacenter/commit/b10f60fbca3dbfabfad65cb3c06e33e19dbcf2e7) add `filter_woys` and `max_loop` param on drought update function to better control update process. 
```python
from geodb.tasks import downloadtif_task
downloadtif_task.delay()
```
That script update latest 1 week drought data.  It should be called using `celery call` but not working, still investigating.

**Comment by dodiws** [comment]
After tweak celery setting, drought update for latest 1 week can be called using:
```
./manage.py celery call geodb.tasks.downloadtif_task
```
Monitoring the log for progress:
```
tail -f /home/ubuntu/celery_worker.log
```
Updating about 1 year of drought data in progress.

**Comment by rafinkanisa** [comment]
Thank you @dodiws 
Will keep the issue in the progress stage until the data update is finished

**Comment by dodiws** [comment]
Finished updating 46 weeks of drought data, the next weekly update will be done manually every Monday because new data is published every Sunday from the data source.
