### ISSUE TITLE
Hide Humanitarian Access Menu in GeoExplorer for public but visible for iMMAP

### ISSUE THREAD

**Issue by rafinkanisa** [iMMAP/DRR-datacenter#18]
As part of re-activating the ASDC to humanitarian organization, we'll have to hide all of security information related in ASDC as it's considered as a sensitive information that will put risk with the current government

Acceptance Criteria

- [x] Humanitarian Access in GeoExplorer Menu is hidden for public user but visible to the user with iMMAP group

**Comment by dodiws** [comment]
[This commit](https://github.com/iMMAP/DRR-datacenter/commit/88770bb9ec79826c06ee251235ae99c7b6b481d3) restrict Humanitarian Access in GeoExplorer Menu for iMMAP only. Filtering using `org_acronym` attribute.

**Comment by rafinkanisa** [comment]
DONE checking. Looks good. Well done!
