### ISSUE TITLE
Investigate Drought

### ISSUE THREAD

**Issue by rafinkanisa** [iMMAP/DRR-datacenter#5]
As a follow-up action point to support the capacity-building team to deliver the training of Natural Hazard and Geometeorological before this award is ending by the end of this month, we'll need to make ASDC temporarily accept new users.

Since this training is related to Natural Hazard and Geometeorological, one of its focus is on drought.
From the following link, you can see that the closest available prediction is a long time ago.
http://asdc.immap.org/dashboard/?page=drought
<img width="490" alt="Screen Shot 2022-02-04 at 18 52 42" src="https://user-images.githubusercontent.com/28089698/152524931-1cef601c-c594-4481-9ac8-121c9703c700.png">

Kindly let me know whether this was caused by the celery task which doesn't work properly or the data has become unavailable to be retrieved by the platform?

**Comment by sud0su** [comment]
it seems that this is not an error in the celery, because drought is not included in the celery task, it looks like the drought is processed manually or there is a special function running to process drought data, we still need more time to fix it

**Comment by dodiws** [comment]
drought update function is called manually, takes a lot of time to update. will update in the next award
