### ISSUE TITLE
Investigate Earthquake

### ISSUE THREAD

**Issue by rafinkanisa** [iMMAP/DRR-datacenter#6]
As a follow-up action point to support the capacity-building team to deliver the training of Natural Hazard and Geometeorological before this award is ending by the end of this month, we'll need to make ASDC temporarily accept new users.

Since this training is related to Natural Hazard and Geometeorological, one of its focus is on earthquake.
From the following link, you can see that the last data updated 12 months ago.
http://asdc.immap.org/
<img width="387" alt="Screen Shot 2022-02-04 at 18 56 22" src="https://user-images.githubusercontent.com/28089698/152526585-181d9ab3-5814-493a-9927-59d30564383c.png">

Kindly let me know whether this was caused by the celery task which doesn't work properly or the data has become unavailable to be retrieved by the platform?
Also, please check the number of magnitudes that captured by the platform. Was it starting from 5.5 M? Because in the meeting, it has been mentioned that there is an earthquake occurred which doesn't captured by the platform.

**Comment by sud0su** [comment]
we will try to review the celery settings and restart the celery, and also we need to make sure clearly whether the displayed data is at +5M or not, we make sure through the code, database, and response from USGS

**Comment by dodiws** [comment]
Earthquake data update task should working after celery restart. Magnitude 5.5 should appear only if shakemap data available. For data older than 30 days the data update code require modification and manually called. Because of load limit from USGS API the update needs to be divided into multiple batches.
