### ISSUE TITLE
Hide Humanitarian Access Dashboard

### ISSUE THREAD

**Issue by rafinkanisa** [iMMAP/DRR-datacenter#7]
As a follow-up action point to support the capacity-building team to deliver the training of Natural Hazard and Geometeorological before this award is ending by the end of this month, we'll need to make ASDC temporarily accept new users.
It is also required to hide anything related to security.

Because we'll only have a short time to do it, I would propose to temporarily hide the menu of "Humanitarian Access" in the dashboard menu while the training is being conducted.
After the training is finished, we'll put this menu back and will hide the "Humanitarian Access" Dashboard in appropriate manner once we start working for the new award.

TO DO:

- [x] Hide the Humanitarian Access menu in the dashboard for a certain period
- [x] After the training is finished, put back the Humanitarian Access menu

**Comment by sud0su** [comment]
I've pushed the update code to hide the humanitarian URL in the dashboard for a temporary measure, and @dodiws  will do a full review before pulling to the server

**Comment by dodiws** [comment]
Commit tested normal on local machine and has been pulled to server.

**Comment by rafinkanisa** [comment]
Hi. I heard from Daniel that the training is finished. Please put back the menu to be visible @dodiws

**Comment by dodiws** [comment]
Humanitarian Access menu in Dashboard has been re-enabled.
