### ISSUE TITLE
Hide Security Interactive Maps

### ISSUE THREAD

**Issue by rafinkanisa** [iMMAP/DRR-datacenter#9]
As a follow-up action point to support the capacity-building team to deliver the training of Natural Hazard and Geometeorological before this award is ending by the end of this month, we'll need to make ASDC temporarily accept new users.
It is also required to hide anything related to security.

Because we'll only have a short time to do it, I would propose to temporarily take out the permission to see this interactive maps while the training is being conducted.
After the training is finished, we'll put this map back and will hide the map in an appropriate manner once we start working for the new award.

TO DO:

- [x] Hide any interactive maps related with Security
- [x] After the training is finished, put back the interactive map to be visible by anyone

**Comment by sud0su** [comment]
I've updated the permissions for this map, and now only admins can see this map

**Comment by rafinkanisa** [comment]
Hi. I heard from Daniel that the training is finished. Please put back the map to be visible @dodiws

**Comment by dodiws** [comment]
Interactive maps in security category as part of #13 has been re-made visible to public.
